import type { Config } from 'tailwindcss'

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#d2b7ff",
        "on-primary-container": "#220076",
        "surface-container-high": "#1f1f26",
        "primary-dim": "#7556ff",
        "error": "#ff6e84",
        "inverse-surface": "#fcf8ff",
        "on-background": "#f9f5fd",
        "surface-container-low": "#131319",
        "on-tertiary-container": "#5c0036",
        "tertiary-fixed": "#ff8cbd",
        "on-secondary": "#2f006a",
        "error-container": "#a70138",
        "on-secondary-fixed-variant": "#603aa2",
        "secondary-fixed": "#ddc8ff",
        "on-tertiary": "#6b0c41",
        "on-error-container": "#ffb2b9",
        "primary-fixed-dim": "#9581ff",
        "on-surface-variant": "#acaab1",
        "primary-container": "#a391ff",
        "surface-dim": "#0e0e13",
        "inverse-on-surface": "#55545b",
        "surface-container-lowest": "#000000",
        "primary": "#b0a2ff",
        "on-primary": "#2e0096",
        "surface-container-highest": "#25252d",
        "on-surface": "#f9f5fd",
        "primary-fixed": "#a391ff",
        "outline-variant": "#48474d",
        "on-error": "#490013",
        "surface-tint": "#b0a2ff",
        "outline": "#76747b",
        "error-dim": "#d73357",
        "on-primary-fixed": "#000000",
        "background": "#0e0e13",
        "secondary-dim": "#b18af6",
        "on-secondary-fixed": "#431783",
        "inverse-primary": "#5f36f2",
        "tertiary-container": "#fc84b8",
        "tertiary-dim": "#ec77ab",
        "on-tertiary-fixed": "#37001e",
        "secondary-container": "#562f97",
        "tertiary": "#ff9ac3",
        "surface-variant": "#25252d",
        "secondary": "#b38cf9",
        "surface-container": "#19191f",
        "surface": "#0e0e13",
        "on-secondary-container": "#dcc7ff",
        "on-tertiary-fixed-variant": "#6f1044",
        "tertiary-fixed-dim": "#f27db0",
        "surface-bright": "#2c2b33",
        "on-primary-fixed-variant": "#2b0090"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
} satisfies Config
