import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#8FABFF",
        "on-primary-container": "#0F2670",
        "surface-container-high": "#1f1f26",
        "primary-dim": "#2E49C9",
        error: "#ff6e84",
        "inverse-surface": "#fcf8ff",
        "on-background": "#f9f5fd",
        "surface-container-low": "#131319",
        "on-tertiary-container": "#5c0036",
        "tertiary-fixed": "#ffc285",
        "on-secondary": "#1A3A9E",
        "error-container": "#a70138",
        "on-secondary-fixed-variant": "#5A7CE0",
        "secondary-fixed": "#CDDDFF",
        "on-tertiary": "#6b0c41",
        "on-error-container": "#ffb2b9",
        "primary-fixed-dim": "#6A85F6",
        "on-surface-variant": "#acaab1",
        "primary-container": "#3B5BDB",
        "surface-dim": "#0e0e13",
        "inverse-on-surface": "#55545b",
        "surface-container-lowest": "#000000",
        primary: "#3B5BDB",
        "on-primary": "#FFFFFF",
        "surface-container-highest": "#25252d",
        "on-surface": "#f9f5fd",
        "primary-fixed": "#4F6CF7",
        "outline-variant": "#48474d",
        "on-error": "#490013",
        "surface-tint": "#3B5BDB",
        outline: "#76747b",
        "error-dim": "#d73357",
        "on-primary-fixed": "#FFFFFF",
        background: "#0e0e13",
        "secondary-dim": "#8FABFF",
        "on-secondary-fixed": "#0F2670",
        "inverse-primary": "#4F6CF7",
        "tertiary-container": "#FFC285",
        "tertiary-dim": "#FFB347",
        "on-tertiary-fixed": "#3d1a00",
        "secondary-container": "#4F6CF7",
        tertiary: "#FFB347",
        "surface-variant": "#25252d",
        secondary: "#8FABFF",
        "surface-container": "#19191f",
        surface: "#0e0e13",
        "on-secondary-container": "#CDDDFF",
        "on-tertiary-fixed-variant": "#6f1044",
        "tertiary-fixed-dim": "#E8A03E",
        "surface-bright": "#2c2b33",
        "on-primary-fixed-variant": "#FFFFFF",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
} satisfies Config;
