import { Router } from "express";
import authRouter from "./endpoints/auth.js";
import resumeRouter from "./endpoints/resume.js";
import jdRouter from "./endpoints/jd.js";
import analysisRouter from "./endpoints/analysis.js";
import roadmapRouter from "./endpoints/roadmap.js";
import userRouter from "./endpoints/user.js";
import feedbackRouter from "./endpoints/feedback.js";
import agentRouter from "./endpoints/agent.js";
import parseRouter from "./endpoints/parse.js";
import negotiationRouter from "./endpoints/negotiation.js";
import chatRouter from "./endpoints/chat.js";
import scrapeRouter from "./endpoints/scrape.js";
import interviewRouter from "./endpoints/interview.js";
import latexRouter from "./endpoints/latex.js";
import coverLetterRouter from "./endpoints/coverLetter.js";
import skillsTrendRouter from "./endpoints/skillsTrend.js";
import recruiterRouter from "./endpoints/recruiter.js";

import transformerRouter from "./endpoints/transformers.js";
import jobTrackerRouter from "./endpoints/jobTracker.js";
import progressRouter from "./endpoints/progress.js";
import linkedinRouter from "./endpoints/linkedin.js";
import resumeVersionsRouter from "./endpoints/resumeVersions.js";
import benchmarkRouter from "./endpoints/benchmark.js";
import negotiationRoleplayRouter from "./endpoints/negotiationRoleplay.js";
import recommendationsRouter from "./endpoints/recommendations.js";

const router = Router();

router.use("/auth", authRouter);
router.use("/resume", resumeRouter);
router.use("/jd", jdRouter);
router.use("/analysis", analysisRouter);
router.use("/roadmap", roadmapRouter);
router.use("/user", userRouter);
router.use("/feedback", feedbackRouter);
router.use("/agent", agentRouter);
router.use("/parse", parseRouter);
router.use("/negotiation", negotiationRouter);
router.use("/chat", chatRouter);
router.use("/scrape", scrapeRouter);
router.use("/interview", interviewRouter);
router.use("/latex", latexRouter);
router.use("/cover-letter", coverLetterRouter);
router.use("/skills-trend", skillsTrendRouter);
router.use("/recruiter", recruiterRouter);
router.use("/payments", (await import("./endpoints/payments.js")).default);
router.use("/transformers", transformerRouter);
router.use("/jobs", jobTrackerRouter);
router.use("/progress", progressRouter);
router.use("/linkedin", linkedinRouter);
router.use("/resume-versions", resumeVersionsRouter);
router.use("/benchmark", benchmarkRouter);
router.use("/negotiation-roleplay", negotiationRoleplayRouter);
router.use("/recommendations", recommendationsRouter);

export default router;
